import {Card} from "antd";
import React from "react";

const {Meta} = Card;


export default function Politicas() {

    return (
        <Card
            cover={<img alt="example"
                        src="https://porfirios.com.mx/blog/wp-content/uploads/2019/03/Apertura-TOREO-blog-604x270.png"/>}
        >
            <Meta title="POLÍTICAS DE PRIVACIDAD E-MARKET" description={"\n" +
            "Esta Política de Privacidad describe cómo manejamos la información personal recopilada, utilizada y compartida cuando un visitante o cliente accede a E-MARKET.\n" +
            "SECCIÓN 1 - INFORMACIÓN TRANSACCIONAL • ¿Qué hacesmos con tu información?\n" +
            "Cuando compras algo en nuestra tienda, como parte del proceso de compra y venta, recogemos la información personal que nos das como tu nombre, dirección y correo electrónico.\n" +
            "Cuando navega por nuestra tienda, también recibimos automáticamente la dirección del protocolo de Internet (IP) de su ordenador para que nos proporcione información que nos ayude a conocer su navegador y su sistema operativo.\n" +
            "Marketing por correo electrónico (si corresponde):\n" +
            "Con su permiso, podemos enviarle correos electrónicos sobre nuestra tienda, nuevos productos y otras actualizaciones.\n" +
            "SECCIÓN 2 – CONSENTIMIENTO\n" +
            "• ¿Cómo consigues mi consentimiento?\n" +
            "Cuando nos proporciona información personal para completar un pago, hacer un pedido o devolver una compra, implicamos que da su consentimiento para que la recojamos y la utilicemos sólo por esa razón específica.\n" +
            "Si le solicitamos su información personal por una razón secundaria, como la comercialización, le pediremos directamente su consentimiento expreso o le daremos la oportunidad de decir que no.\n" +
            "3\n" +
            "  \n" +
            "• ¿Cómo puedo retirar mi consentimiento?\n" +
            "Después de que usted opte por ello, si cambia de opinión, puede retirar su consentimiento para que nos pongamos en contacto con usted, para la continua recopilación, uso o divulgación de su información, en cualquier momento, poniéndose en contacto con nosotros.\n" +
            "SECCIÓN 3 – DIVULGACIÓN • ¿Revela mi información?\n" +
            "Podemos revelar su información personal si la ley nos obliga a hacerlo o si usted viola nuestros Términos de Servicio.\n" +
            "SECCIÓN 4 - TIENDA EN LÍNEA • El pago por paypal:\n" +
            "Si elige una pasarela de pago directo para completar su compra, la tienda online transmite los datos de su tarjeta de crédito. Los datos de la tienda se encriptan a través del Estándar de Seguridad de Datos de la Industria de Tarjetas de Pago (PCI-DSS). Los datos de la transacción de compra se almacenan sólo el tiempo necesario para completar la transacción de compra. Una vez completado, la información de su transacción de compra se borra.\n" +
            "Todas las pasarelas de pago directo se adhieren a las normas establecidas por el PCI-DSS, gestionadas por el Consejo de Normas de Seguridad del PCI, que es un esfuerzo conjunto de marcas como Visa, MasterCard, American Express y Discover.\n" +
            "Los requisitos del PCI-DSS ayudan a garantizar el manejo seguro de la información de las tarjetas de crédito por parte de nuestra tienda y sus proveedores de servicios.\n" +
            "SECCIÓN 5 - SERVICIOS DE TERCEROS\n" +
            "En general, los terceros proveedores que utilizamos sólo recogerán, utilizarán y divulgarán su información en la medida necesaria para permitirles realizar los servicios que nos proporcionan.\n" +
            "Sin embargo, ciertos terceros proveedores de servicios, como las pasarelas de pago y otros procesadores de transacciones de pago, tienen sus propias políticas de privacidad con respecto a la información que se nos pide que les proporcionemos para sus transacciones relacionadas con la compra.\n" +
            "En el caso de estos proveedores, le recomendamos que lea sus políticas de privacidad para que pueda comprender la manera en que estos proveedores manejarán su información personal.\n" +
            "4\n" +
            "   \n" +
            "5\n" +
            "En particular, recuerde que ciertos proveedores pueden estar situados o tener instalaciones que se encuentran en una jurisdicción diferente a la suya o la nuestra. Por lo tanto, si decide proceder con una transacción que implique los servicios de un tercer proveedor de servicios, su información puede quedar sujeta a las leyes de la(s) jurisdicción(es) en la(s) que se encuentre ese proveedor de servicios o sus instalaciones.\n" +
            "Por ejemplo, si usted se encuentra en Canadá y su transacción se procesa a través de una pasarela de pago ubicada en los Estados Unidos, entonces su información personal utilizada para completar esa transacción puede estar sujeta a la divulgación en virtud de la legislación de los Estados Unidos, incluida la Ley Patriota.\n" +
            "Una vez que abandone el sitio web de nuestra tienda o sea redirigido a un sitio web o aplicación de terceros, ya no se regirá por esta Política de Privacidad ni por los Términos de Servicio de nuestro sitio web.\n" +
            "• Enlaces\n" +
            "Cuando haces clic en los enlaces de nuestra tienda, pueden dirigirte fuera de nuestro sitio. No nos hacemos responsables del contenido o de las prácticas de privacidad de otros sitios y le animamos a que lea sus declaraciones de privacidad.\n" +
            "SECCIÓN 6 - SEGURIDAD\n" +
            "Para proteger su información personal, tomamos precauciones razonables y seguimos las mejores prácticas de la industria para asegurarnos de que no se pierda, se use mal, se acceda a ella, se divulgue, se altere o se destruya de forma inapropiada.\n" +
            "Si usted nos proporciona la información de su tarjeta de crédito, la información se codifica utilizando la tecnología de capa de conexión segura (SSL) y se almacena con la codificación AES-256. Aunque ningún método de transmisión por Internet o de almacenamiento electrónico es 100% seguro, seguimos todos los requisitos del PCI-DSS e implementamos estándares adicionales generalmente aceptados por la industria.\n" +
            "SECCIÓN 7 - NO RASTREE\n" +
            "Nuestro sitio web utiliza \"Cookies\" como archivos de datos que se colocan en su dispositivo o computadora y a menudo incluyen un identificador único anónimo. Para obtener más información sobre las cookies y cómo deshabilitarlas, visite http://www.allaboutcookies.org.\n" +
            "Tenga en cuenta que no alteramos la recopilación de datos y las prácticas de uso de nuestro sitio web cuando vemos una señal de \"No rastrear\" en su navegador.\n" +
            " \n" +
            "SECCIÓN 8 - EDAD DE CONSENTIMIENTO\n" +
            "Al utilizar este sitio, usted declara que tiene al menos la mayoría de edad en su estado o provincia de residencia, o que es mayor de edad en su estado o provincia de residencia y nos ha dado su consentimiento para permitir que cualquiera de sus dependientes menores de edad utilice este sitio.\n" +
            "SECCIÓN 9 - CAMBIOS EN ESTA POLÍTICA DE PRIVACIDAD\n" +
            "Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento, así que por favor revísela con frecuencia. Los cambios y aclaraciones entrarán en vigor inmediatamente después de su publicación en el sitio web. Si realizamos cambios materiales en esta política, le notificaremos aquí que ha sido actualizada, para que esté al tanto de qué información recogemos, cómo la usamos y bajo qué circunstancias, si las hay, la usamos y/o revelamos.\n" +
            "Si nuestra tienda se adquiere o se fusiona con otra empresa, su información puede ser transferida a los nuevos propietarios para que podamos seguir vendiéndole productos.\n" +
            "PREGUNTAS E INFORMACIÓN DE CONTACTO\n" +
            "Si desea: acceder, corregir, modificar o eliminar cualquier información personal que tengamos sobre usted, registrar una queja, o simplemente quiere más información, póngase en contacto con nuestro Oficial de Cumplimiento de la Privacidad en o por correo electrónico en E-MARKET\n" +
            "OLIMPO\n" +
            "Ciudad de México, México.\n" +
            "6\n" +
            "\n" +
            "2.- Términos y Condiciones\n" +
            "Términos y Condiciones del uso de la plataforma “E-Market”\n" +
            "ASPECTOS GENERALES RELACIÓN CONTRACTUAL:\n" +
            "Los presentes Términos y Condiciones de uso regulan el acceso o uso que usted haga, como persona, desde los Estados Unidos Mexicanos de la aplicación E-Market compuesto por servicios web puestos a disposición por Olimpo S. en C.S.\n" +
            "FAVOR DE LEER TODAS LAS CONDICIONES ANTES DE ACCEDER O HACER USO DE LOS SERVICIOS\n" +
            "Mediante la aceptación de estos términos y condiciones se regula e l acceso y uso de los Servicios y son los que establecen una relación contractual entre usted y E-Market. Si usted no acepta dichos Términos y Condiciones, no podrá acceder o usar los Servicios. Estos Términos y Condiciones sustituyen expresamente los acuerdos o compromisos previos celebrados entre las partes. E-Market podrá poner fin de inmediato a estos Términos y Condiciones o cualquiera de los Servicios respecto de usted o, en general, dejar de ofrecer o denegar el acceso a los Servicios o cualquier par te de ellos, en cualquier momento y por cualquier motivo de manera unilateral.\n" +
            "Se podrán aplicar condiciones suplementarias a determinados Servicios, como políticas para una promoción particular, y dichas condiciones suplementarias se le comunicarán en relación con los Servicios aplicables. Las condiciones suplementarias se establecen además de los Términos y Condiciones, y se considerarán una parte de estas, para los fines de los Servicios aplicables.\n" +
            "E-Market podrá modificar los Términos y Condiciones relativos a los Servicios cuando lo considere oportuno. Las modificaciones serán efectivas después de la publicación por parte de E-Market de dichos Términos y Condiciones actualizadas o las políticas modificadas o condiciones suplementarias sobre el Servicio aplicable. Su acceso o uso continuado de los Servicios después de dicha publicación constituye su consentimiento a vincularse por los Términos y Condiciones y sus modificaciones.\n" +
            "La recopilación y el uso que realiza E-Market de la información personal en relación con los Servicios se efectúa de acuerdo con la Política de privacidad de E-Market\n" +
            "NATURALEZA JURÍDICA:\n" +
            "Los presentes Términosy Condiciones de uso regulan propiamente la relación contractual de carácter comercial que vincula a los Consumidores que acceden y/o usan la aplicación web y al Operador, especialmente en la autorización de uso que otorga éste en favor de aquel como también el uso que los Consumidores dan a la Plataforma.\n" +
            "DEFINICIONES:\n" +
            "7\n" +
            "\n" +
            "8\n" +
            "Cookies:CadenasdetextoenviadasvirtualmentequesonalmacenadasporelusodelaAplicación por el Operador, para la consulta de las actividades y preferencias de los usuarios.\n" +
            "Comercio Electrónico: Comprende el envío, transmisión, recepción, almacenamiento de mensajes de datos por vía electrónica. Las dudas que surjan respecto de la eficacia y validez de los mensajes de datos y demás actividades vinculadas al comercio electrónico se interpretarán de conformidad con el Capítulo VIII BIS de la Ley Federal de Protección al Consumidor.\n" +
            "Contrato de mandato remunerado celebrado por medios electrónicos: Aquel acuerdo de voluntades celebrado entre el Consumidor y el Comisionista, por medio del cual el Consumidor solicita, a través de la plataforma la gestión de un encargo al comisionista, obligándose este último a cumplir con dicho encargo por cuenta y riesgo del Consumidor, a cambio de recibir una remuneración como contraprestación.\n" +
            "Comisionista: Persona física que acepta realizar la gestión del encargo solicitado por el Consumidor a través de la Aplicación. El Comisionista reconoce que presta el Servicio por cuenta y riesgo propio y libera al Consumidor de cualquier responsabilidad que pudiera surgir durante la prestación del servicio.\n" +
            "Consumidor(es):Quien(es)accede(n)y/ousa(n)elserviciowebparasolicitar pormediodebieneso servicios.\n" +
            "Datos Personales: Es toda información que permite identificar o hacer identificable a una persona física.\n" +
            "Interacción en la Plataforma: Facultad de los Consumidores para conocer los productos exhibidos por el Operador, así como la publicidad puesta a disposición en la Plataforma.\n" +
            "Mayor de edad: Persona física mayor de dieciocho (18) años.\n" +
            "Mensajes de Datos: La información generada, enviada, recibida, almacenada o comunicada por medios electrónicos, ópticos o similares, como pudieran ser, entre otros, el Intercambio Electrónico de Datos (EDI).\n" +
            "Producto(s): Exclusivamente aquellos bien(es) de consumo exhibido(s) a través de la Plataforma. Ventanas Emergentes (Pop-Ups): Ventana o aviso de internet que emerge automáticamente en\n" +
            "cualquier momento cuando se utiliza la Plataforma.\n" +
            "Plataforma: Aplicación web y móvil administrada por el Operador que permite la concurrencia en un mercado de Consumidores y Comisionistas.\n" +
            "Pasarela de Pagos: Servicio que permite la realización de pagos por parte de los Consumidores directamente a los Comisionistas a través de medios electrónicos utilizando plataformas tecnológicas (software).\n" +
            "OBJETO DE LOS TÉRMINOS Y CONDICIONES:\n" +
            "Los presentes Términos y Condiciones regulan la autorización de uso que otorga el Operador a los Consumidores, para que éstos ingresen a la Plataforma virtual, se informen sobre los Productos de consumo exhibidos para que sean utilizados como referencia y puedan solicitar la gestión de un encargo por medio de un contrato de mandato con el Comisionista.\n" +
            "El Operador, a través de la Plataforma realiza, de manera limitativa, las siguientes acciones:\n" +
            "\n" +
            "9\n" +
            "(i) exhibe diferentes productos de consumo de forma publicitaria para que puedan servir de referencia a los Consumidores; (ii) facilita el encuentro entre Consumidores y Comisionistas para la realización del vínculo contractual; (iii) permite el uso de la Pasarela de Pagos, sin que en este proceso implique vínculo alguno con el Operador, ya que por la tecnología implementada el pago se realiza directamente a los Comisionistas\n" +
            "Lacelebracióndela relacióncontractualentreConsumidoresyComisionista,sedaconConsumidores que se encuentren en el territorio nacional.\n" +
            "A través de la Plataforma se exhiben Productos, cuya gestión de compra es encargada por los Consumidores a los Comisionistas, siendo que los primeros buscan satisfacer una necesidad privada, personal o familiar, y en ningún momento pretenden la comercialización, reventa o cualquier otro tipo de transacción comercial o interés con los productos adquiridos.\n" +
            "LICENCIA:\n" +
            "SujetoalcumplimientodelospresentesTérminosyCondiciones,E-MarketotorgaalosConsumidores una autorización limitada, no exclusiva, revocable, no transferible para: (i) el acceso y uso de la plataforma para el uso de los Servicios; y (ii) el acceso y uso de cualquier contenido, información y material relacionado que pueda ponerse a disposición a través de los Servicios, en cada caso solo para su uso personal, no comercial. E-Market y sus licenciantes se reservan cualquier derecho que no haya sido expresamente otorgado por los presentes Términos y Condiciones.\n" +
            "LOS SERVICIOS:\n" +
            "El Operador exhibe a través de La Plataforma productos de consumo como alimentos y bebidas que están a disposición de los Consumidores para su conocimiento general. Esta comunicación de productos sirve como referencia a los Consumidores para poder usar La Plataforma como medio para solicitar lagestióndeunencargodecompraventa,celebrándoseuncontratodemandatoremunerado con el Comisionista.\n" +
            "OBJETO DE LOS SERVICIOS:\n" +
            "El Consumidor reconoce y acepta usar la Plataforma como un medio de encuentro con Comisionistas para la solicitud de encargos y de esta manera lograr la adquisición de Productos para su consumo final y la satisfacción de sus necesidades, con sujeción a la normatividad mercantil mexicana.\n" +
            "El uso de la Plataforma lo realiza el Consumidor como persona capaz y mayor de edad, y manifestando que, para la celebración del contrato de Mandato con los Comisionistas, cuenta con plena capacidad legal para ser sujeto de derechos y obligaciones, calidades que refrenda al momento de generar su registro.\n" +
            "El Consumidor reconoce expresamente mediante la aceptación de los presentes Términos y Condiciones de uso de la Plataforma que E-Market no será responsable en ningún momento de cualquier producto que los Consumidores requieran y adquieran a través de la Plataforma. Asimismo, E-Market tampoco podrá observar y verificar el correcto funcionamiento d e la Plataforma en relación cualquier otro producto distinto a aquellos exhibidos en la Plataforma.\n" +
            "\n" +
            "10\n" +
            "Los Comisionistas, teniendo capacidad de contratación, acceden a la Plataforma y aceptan realizar la gestión de los encargos solicitados por los Consumidores, entendiéndose que dicha aceptación es meramente voluntaria.\n" +
            "El perfeccionamiento del contrato de mandato celebrado por medios electrónicos se da en el momento en que el Comisionista acepta la gestión del encargo solicitado por el Consumidor. Se aclara que el Comisionista únicamente puede aceptar el encargo, una vez el Consumidor haya seleccionado el medio de pago. Por lo tanto, verificados los pasos de proceso de compra, el Comisionista, por intermedio del Operador puede aceptar total o parcialmente la gestión del encargo solicitado por el Consumidor. En caso de aceptar el encargo únicamente de manera parcial, el resumen se actualizará evidenciando los Productos sobre los cuales efectivamente se entiende constituido el encargo.\n" +
            "CUENTA DE USUARIO:\n" +
            "Los Consumidores usan como referencia para su compra los Productos que se encuentran exhibidos en la Plataforma, teniendo como condición indispensable la creación de una cuenta de usuario (en adelante la “Cuenta de Usuario”), donde se solicitarán datos como nombre, fecha de nacimiento, teléfono, dirección de correo electrónico; esta información se utiliza para (i) la plena identificación de los Consumidores que pretenden adquirir los Productos, para (ii) el cumplimiento de la Compraventa, para (iii) la prevención de fraudes, para (iv) vincular al Consumidor con el Comisionista y en general para los fines definidos en el capítulo correspondiente al Manejo de información.\n" +
            "Una vez suministrada la información necesaria para el uso de la Plataforma, se validará por p arte del Operador el nombre de usuario y contraseña para acceder y/o usar la Plataforma.\n" +
            "El uso de la Cuenta de Usuario es personal e intransferible, por lo cual los Consumidores no se encuentran facultados para ceder los datos de validación para el acceso a la Plataforma. En caso de olvido de los datos de validación o de usurpación de éstos, es obligación del Consumidor informarlo al Operador a través de la opción “olvidó su contraseña”.\n" +
            "Las cuentas de usuarios serán administradas por el Operador a su dis creción o por la persona que éste designe, teniendo plena facultad para la conservación o no de la cuenta, cuando la información suministrada por los Consumidores no sea veraz, completa o segura; o cuando se presente incumplimiento de las obligaciones de los Consumidores.\n" +
            "En ningún momento el Operador solicitará al Consumidor información que NO resulte necesaria para su vinculación con el Comisionista y para la facilitación del pago, por lo que los datos de tarjetas débito o crédito, solo se solicitarán al momento de realizar el pago virtual si así lo determina el Consumidor, éstos datos no serán almacenados por el Operador, serán inscritos directamente en la Pasarela de Pagos correspondiente, y se utilizarán directamente por el Consumidor en ésta, donde se informará las condiciones de seguridad y privacidad en que se efectúa el mismo.\n" +
            "Con la creación de la Cuenta de Usuario, los Consumidores están manifestando su voluntad de aceptación expresa e inequívoca de los presentes Términos y Condiciones de uso de la Plataforma.\n" +
            "Al momento de la aceptación de los presentes Términos y Condiciones, expresamente el Consumidor autoriza el uso de Cookies por parte del Operador en toda actividad de uso que realice en la Plataforma.\n" +
            "\n" +
            "CAPACIDAD:\n" +
            "Manifiesta el Consumidor que la relación contractual que se puede llegar a generar por el uso de la Plataforma será directamente y exclusivamente con los Comisionistas, y consistirá en un mandato celebrado por medios electrónicos, en el cual el Consumidor es el mandante.\n" +
            "En virtud de las condiciones de capacidad legal establecidas en la legislación mexicana vigente y de la validez de la manifestación de voluntad a través de medios electrónicos establecida en el Código Civil Federal, los Consumidores al momento de la creación de la Cuenta de Usuario, manifiestan expresamente tener capacidad suficiente para celebrar el tipo de contrato de mandato, que se puede o podría llegar a configurar accediendo y/o usando la Plataforma; y no obstante lo anterior, los menores de edad de acuerdo con la ley aplicable, no están facultados para hacer uso en ningún momento de la Plataforma provocando así la nulidad de todo mandato generado en la Plataforma en caso de contravención a lo que aquí establecido.\n" +
            "DESCRIPCIÓN DEL SERVICIO:\n" +
            "El Operador exhibe a través de la Plataforma Productos de consumo como alimentos, bebidas, productos de aseo personal y productos de aseo general, que están a disposición de los Consumidores para su conocimiento general. Esta comunicación de productos sirve como referencia a los Consumidores para su adquisición, usando la Plataforma como medio para solicitar la gestión de encargos a los Comisionistas y celebrar un contrato de mandato por medios electrónicos.\n" +
            "Para poder solicitar el mandato y de esta forma adquirir los bienes y servicios deseados, los Consumidores deben estar plenamente identificados en su Cuenta de Usuario y seguir el siguiente procedimiento:\n" +
            "1. Seleccionar un restaurante, ya sea de la sección “Mis Restaurantes” o bien de las sugeren cias mostradas en la plataforma.\n" +
            "2. Seleccionar el (los) Producto(s). Al seleccionar el (los) Producto(s) se pone a disposición del Consumidor las características y valor total del (los) Producto(s) por medio de fotografías y notas de referencias, que permiten la plena individualización del (los) Producto(s) para el análisis detallado del Consumidor.\n" +
            "3. Validación del (los) Producto(s). Cumplido el paso anterior, el Operador deberá exhibir al Consumidor un resumen de (los) Producto(s) en cuanto a sus condiciones generales tales como los ingredientes y la presentación suministrada. Con ésta información el Consumidor podrá validar el (los) Producto(s) seleccionado(s), para que sea usado como referencia con relación al producto que pretende adquirir.\n" +
            "4. Ingreso del (los) Producto(s) al carrito de compras. Este ingreso corresponde a la voluntad inequívoca del Consumidor de adquirir algún Producto determinado, ya que se ha informado con suficiencia las características del mismo, teniendo la posibilidad de adquirirlo o no. El Operador tiene total autonomía para limitar el ingreso del (los) Producto(s) al carrito de compras con ocasión a la cantidad.\n" +
            "5. Precio. Una vez se han agotados los pasos precedentes, se pone a disposición del Consumidor el Precio a pagar por el (los) Productos seleccionado(s), el cual se encuentra reflejado unitariamenteyenconjuntoportodoslosProductosaadquirir.Elvalorcorresponderáalvalor total del (los) Producto(s) incluyendo costos de envío, de transacción e impuestos. En ese mismo sentido, E-Market se reserva el derecho de incrementar, hasta en un diez por ciento (10%), los precios de los productos exhibidos en las tiendas físicas de sus aliados. El usuario\n" +
            "11\n" +
            "\n" +
            "12\n" +
            "reconoce y acepta la anterior condición e igualmente tampoco realizará ningún tipo de reclamación frente a E-Market por cobros adicionales a los precios que se vean reflejados en tickets de venta. Los valores adicionales serán cobrados a título de uso de la plataforma virtual.\n" +
            "6. Pago. El pago que realiza el Consumidor lo realiza directa y exclusivamente con los Comisionistas, en ningún momento el dinero ingresará en beneficio del Operador.\n" +
            "7. Forma de pago. El Consumidor deberá seleccionar el medio de pago que desea utilizar, teniendo como posibilidades el pago contra-entrega a través de i) dinero en efectivo o ii) el pago electrónico a través de la Pasarela de Pago contratada por el Operador, siempre y cuando ésta se encuentre disponible en la aplicación. En este momento se configura la solicitud del encargo que realiza el Consumidor al Comisionista.\n" +
            "8. Registro. Al momento de definir la forma de pago, el Consumidor deberá crear su cuenta personal en la cual se requerirán los datos personales que permitan su identificación, más no su individualización. Adicionalmente, se requerirán los datos para poder realizar el pago de manera electrónica.\n" +
            "9. Resumen y Correo electrónico. Una vez completados los pasos anteriores se le exhibirá a través de una ventana emergente al Consumidor, un resumen detallado de la transacción y la información completa del Comisionista, que ha aceptado realizar la gestión del encargo y con el cual se celebra el mandato.\n" +
            "10. Recibo. En todo caso, sea que el pago realice en dinero en efectivo o a través de la Pasarela de Pagos, se le dará la opción para descargar un archivo con los detalles del pago.\n" +
            "OBLIGACIONES DEL CONSUMIDOR:\n" +
            "Con la aceptación de los presentes Términos y Condiciones de uso de la Plataforma, el Consumidor se obliga a: (1) Suministrar información veraz y fidedigna al momento de crear su propia Cuenta de Usuario; (2) Abstenerse de transferir a terceros los datos de validación (nombre de usuario y contraseña); (3) Abstenerse de acceder y/o usar la Plataforma para realizar actos contrarios a la moral, al orden público, a las buenas costumbres o actos o hechos ilícitos en contra del Operador, los Comisionistas o de terceros; (4) Pagar oportunamente al Comisionista la contraprestación económica definida en el proceso de compra; (5) Informar inmediatamente al Operador en caso de olvido o usurpación de los datos de validación; (6) Abstenerse de realizar conductas atentatorias del funcionamiento de la Plataforma; (7) Abstenerse de requerir a los Comisionistas cualquier otro producto cuya comercialización, venta o distribución por teléfono, correo, internet o cualquier otro medio de comunicación sea prohibida por la legislación aplicable; (8) Abstenerse de suplantar la identidad de otros Consumidores; (9) Abstenerse de descifrar, descompilar o desensamblar, apropiarse de cualquier elemento de la Plataforma o de cualquiera de sus partes; (10) Habilitar la utilización de ventanas emergentes durante la operación de la Plataforma; (11) En general, todas aquellas conductas necesarias para la ejecución del negocio jurídico, como i) la recepción de los productos solicitados, ii) exhibir la identificación en caso de compra de productos de uso restringido, iii) verificar al momento de la validación que los Productos seleccionados si corresponden a los necesitados, iv) informarse sobre las instrucciones de uso y consumo de los Productos, pagar el precio al Comisionista; 12) Sacar en paz y salvo a E-Market de cualquier reclamación de naturaleza jurídica en su contra y a asumir de manera personal, de manera enunciativa más no limitativa, las consecuencias relativas a la licitud, calidad, imagen, presentación, tamaño, color, precio, etc., de aquel(los) producto(s) distintos al (los) Producto(s) exhibidos en la Plataforma y que sean requeridos por los Consumidores a través de la Plataforma. V) En caso de requerir factura, debe informarle al Comisionista para que le proporcione la factura por el costo del (los) servicio(s) brindado (s).\n" +
            "\n" +
            "DEBERES DEL OPERADOR:\n" +
            "En virtud de los presentes Términos y Condiciones de uso, el Operador se obliga a (1) suministrar información cierta, fidedigna, suficiente, clara y actualizada respecto de los Productos que exhibe; (2) Indicar las características generales del (los) Producto(s) para que sirvan de referencia a los Consumidores, para el efecto son marca y presentación; (3) Informar suficientemente sobre los medios habilitados para que los Consumidores realicen el pago; (4) Informar en el momento indicado y con suficiencia los datos de los Comisionistas con los cuales los Consumidores han de celebrar el contrato de mandato; (5) Poner a disposición de los Consumidores los Términos y Condiciones de uso de la Plataforma de forma actualizada; (6) Utilizar la información únicamente para los fines establecidos en los presentes Términos; (7) Utilizar mecanismos de información y validación durante la transacción como ventanas emergentes (Pop Ups), que permitan al Consumidor aceptar o no cada paso del proceso de compra.\n" +
            "DESCRIPCIÓN DE LOS PRODUCTOS:\n" +
            "Los Productos exhibidos por el Operador son productos de consumo doméstico como alimentos y bebidas. Todos los Productos cuentan con una descripción general; esta descripción se realiza por el Operador a partir de prácticas legales de visualización, que e n todo caso dependen el dispositivo en donde el Consumidor observe el (los) Producto(s). La disponibilidad será definida en cada caso en concreto al momento en que el Comisionista realice la gestión encargada y consecuentemente obtenga (los) Producto(s) ante proveedores. Dentro del proceso de compra, el Consumidor determinará qué acción debe realizar el Comisionista en caso de no hallar el (los) Producto(s) solicitado(s), entre las siguientes opciones: (i) Cumplir con el pedido excluyendo el (los) Producto(s) solicitado(s) no hallados, caso en el cual se descontará su costo del valor total del pedido y, en caso de ser sólo un Producto y no se halla, deberá elegir entre la cancelación del pedido o el cumplimiento con un producto sustituto o similar en precio y tipo; (ii) Comunicarse con el Consumidor para concertar el cumplimiento con un producto sustituto; y (iii) Autorizar al Comisionista para llevar un producto similar en precio y tipo.\n" +
            "Reconoce el Consumidor que el Operador no es productor, proveedor, expendedor, agente, distribuidor y en general ningún tipo de comercializador de los productos que exhibe, ya que opera solo como una plataforma tecnológica que permite el encuentro de Consumidores y Comisionistas para la solicitud de encargos. El ticket de ve nta que emitan los comercios aliados al Operador a favor del usuario, no necesariamente reflejará el método de pago seleccionado por el usuario en la plataforma virtual.\n" +
            "Los Productos de uso restringido, tales como aquellos que requieren que el Consumidor sea mayor de edad, solo se entregarán por parte del Comisionista a Consumidores que cuenten con mayoría de edad, quienes manifiestan expresamente esta calidad al momento de aceptar los presentes Términos y Condiciones como también al registrarse y de seleccionar el (los) Producto(s). En caso de no cumplir con ésta obligación, el Comisionista no aceptará la transacción y en el evento de haber pagado por el (los) Producto(s), tendrá la posibilidad definir con el Comisionista el mecanismo para la devolución de l dinero. En el caso de haber solicitado junto con los Productos de uso restringido otros de diferente tipo y/o calidad e igualmente se incumpla la obligación aquí descrita, aplicarán las mismas consecuencias jurídicas aquí definidas, pero solo en relación con los Productos de uso restringido.\n" +
            "13\n" +
            "\n" +
            "14\n" +
            "ElOperadorsereservaelderechodeactualizar,modificary/odescontinuarencualquiermomentolos Productos exhibidos en la Plataforma.\n" +
            "GARANTÍA:\n" +
            "Entiende y acepta el Consumidor que la relación comercial se genera directamente con los Comisionistas, por lo tanto las reclamaciones por garantía se deben realizar directamente con los Comisionistas, quienes tienen la obligación de cumplir con las reclamaciones en los términos de las leyes aplicables.\n" +
            "FUNCIONAMIENTO DE LA PLATAFORMA:\n" +
            "El Operador administra directamente o por medio de terceras personas la Plataforma, toda la información que se comunica allí corresponde a información cierta y actualizada. En ningún caso responderá por daños directos o indirectos que sufra el Consumidor por la utilización o incapacidad de utilización de la Plataforma.\n" +
            "La Plataforma se encuentra disponible las 24 (veinte y cuatro) horas del día para su acceso y consulta. Para la realización de transacciones la disponibilidad de la Plataforma es de 24 (veinte y cuatro) horas al día, dependiendo de la disponibilidad de los Comisionistas y de los proveedores de los Productos. ElOperadorrealizarálosmejoresesfuerzosparamantenerenoperaciónlaPlataforma,peroenningún caso garantiza disponibilidad y continuidad permanente de la Plataforma.\n" +
            "El Operador se reserva el derecho de cancelar cualquier Cuenta de Usuario y/o de prohibir el acceso a la Plataforma a cualquier Consumidor que realice conductas violatorias de los presentes Términos y Condiciones o que incumplan las obligaciones contraídas.\n" +
            "DERECHO DE RETRACTO:\n" +
            "Debido a que los Productos que se exhiben a través de la Plataforma son productos perecederos, el Operador informa a los Consumidores que los Comisionistas no se encuentran o bligados a otorgar el derecho de retracto o ningún tipo de derecho similar que podría corresponderle.\n" +
            "COMERCIO ELECTRÓNICO:\n" +
            "En cumplimiento de las disposiciones mexicanas sobre mensajes de datos según el Código Civil Federal, se comunica que la legislación mexicana reconoce validez a los mensajes por medios electrónicosyportantoellos adquierencarácteryentidadprobatoria.Enconsecuencia,entiendenlos Consumidores, que mediante el cruce de mensajes por medios electrónicos, el Consumidor y los Comisionistas pueden dar lugar al nacimiento, modificación y extinción de obligaciones, siendo de su resorte exclusivo el contenido, consecuencias, responsabilidades y efectos de la información generada.\n" +
            "La transacción comercial que nace por este medio entre Consumidores y Comisionistas, es la celebración de un contrato de mandato por medios electrónicos, el cual se describe en la ventana emergente que acepta el Consumidor al momento de la celebración del negocio jurídico. En ningún\n" +
            "\n" +
            "15\n" +
            "momento se configura alguna relación contractual diferente como suministro, distribución o demás similares.\n" +
            "MANEJO DE INFORMACIÓN:\n" +
            "La información recolectada por el Operador en las transacciones realizadas, es suministrada por los Consumidores de forma libre y voluntaria, para que e sta sea administrada por el Operador o por quien éste designe para el cumplimiento de los deberes adquiridos, lo que implica su recolección; almacenamiento en servidores o repositorios del Operador o de terceros; circulación de los mismos dentro de la organización del Operador; comunicación a los Consumidores información comercial, publicitaria y de mercadeo relacionada con su actividad comercial.\n" +
            "Asimismo, los datos recolectados serán objeto de análisis para fines de mejorar la estrategia de negocios del portal web, apoyada en herramientas de inteligencia de negocios y minería de datos, que permiten adquirir conocimientos prospectivos para fines de predicción, clasificación y segmentación.\n" +
            "El Operador es responsable del tratamiento de la información person al recolectada a través del portal web, responsabilidad que podrá delegar en un tercero, en calidad de responsable o encargado de la información, asegurando contractualmente adecuado tratamiento de la misma.\n" +
            "Asimismo, al aceptar los presentes términos y condiciones el Consumidor manifiesta expresamente haber leído y aceptado el aviso de privacidad del Operador.\n" +
            "ACEPTACIÓN TOTAL DE LOS TÉRMINOS:\n" +
            "El Consumidor manifiesta expresamente tener capacidad legal para usar la Plataforma y para celebrar los contratos de mandato que se puedan generar con los Comisionistas. Asimismo, manifiesta haber suministrado información real, veraz y fidedigna. Por ende, de forma expresa e inequívoca declara que ha leído, que entiende y que acepta la totalidad de los supuestos prev istos y regulados en el presente escrito de Términos y Condiciones de uso de la Plataforma, por lo que se compromete al cumplimiento total de los deberes, obligaciones, acciones y omisiones aquí expresadas.\n" +
            "DOMICILIO Y LEGISLACIÓN APLICABLE\n" +
            "Para lo no previsto en estos Términos y Condiciones, los Consumidores y los Comisionistas acuerdan someterse a las leyes aplicables de la Ciudad de México.\n" +
            "Para la interpretación y ejecución de los presentes Términos y Condiciones, el Consumidor acepta someterse a la jurisdicción y competencia de los tribunales competentes de la Ciudad de México, renunciando expresamente al fuero que pudiese corresponderle por razón de su domicilio presente o futuro, reconociendo que su solución, en su caso, debe hacerse por la vía me rcantil, aplicándose el Código de Comercio y supletoriamente el Código Civil Federal."}/>
        </Card>
    )

}

